language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.7-dev"  # 3.7 development branch         
      dist: xenial          # required for Python >= 3.7
      before_install:
        - sudo apt-get install python3-pyqt5
        - sudo apt-get install texlive
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
        - choco install python
        - wget https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-2.9.6942-x64.zip
        - 7z x miktexsetup-2.9.6942-x64.zip
        - ./miktexsetup.exe --package-set=basic download
        - ./miktexsetup.exe install
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
cache: pip
services: 
  - xvfb
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -vvv
after_success:
  coveralls
