language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.7-dev"  # 3.7 development branch         
      dist: xenial          # required for Python >= 3.7
      before_install:
        - sudo apt-get install python-enchant
        - sudo apt-get install python3-pyqt5
        - sudo apt-get install texlive
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
        - choco install python
        - pip install https://files.pythonhosted.org/packages/83/ff/38ac490f1b8f9e7ff6a8d908b973abf552d35b0e80113149080a14620e40/pyenchant-2.0.0-py2.py3.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp33.pp35-none-win32.whl
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
cache: pip
services: 
  - xvfb
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -vvv
after_success:
  coveralls
